create database ORDER_MANAGEMENT;

use ORDER_MANAGEMENT;

CREATE TABLE ORDER_MANAGEMENT_SERIES(
SERIES_ID int NOT NULL AUTO_INCREMENT,
SERIES_CODE varchar(5) NOT NULL,
SERIES_NAME varchar(20),
IS_ACTIVE varchar(1) DEFAULT 'Y',
CONSTRAINT PK_SERIES PRIMARY KEY (SERIES_ID)
);

CREATE TABLE ORDER_MANAGEMENT_MODEL(
MODEL_ID int NOT NULL AUTO_INCREMENT,
MODEL_NAME varchar(30),
SERIES_ID int NOT NULL,
PRICE decimal(10,2),
IS_ACTIVE varchar(1) DEFAULT 'Y',
CONSTRAINT PK_MODEL PRIMARY KEY(MODEL_ID),
CONSTRAINT FK_MODEL_SERIES FOREIGN KEY (SERIES_ID) references ORDER_MANAGEMENT_SERIES (SERIES_ID)
);

CREATE TABLE ORDER_MANAGEMENT_ACCESSORY(
ACCESSORY_ID int NOT NULL AUTO_INCREMENT,
ACCESSORY_NAME varchar(30),
MODEL_ID int NOT NULL,
PRICE decimal(10,2),
IS_ACTIVE varchar(1) DEFAULT 'Y',
CONSTRAINT PK_ACCESSORY PRIMARY KEY(ACCESSORY_ID),
CONSTRAINT FK_ACCESSORY_MODEL FOREIGN KEY (MODEL_ID) references ORDER_MANAGEMENT_MODEL (MODEL_ID)
);

CREATE TABLE ORDER_MANAGEMENT_COLOR(
COLOR_ID int NOT NULL AUTO_INCREMENT,
COLOR_NAME varchar(30),
MODEL_ID int NOT NULL,
PRICE decimal(10,2),
IS_ACTIVE varchar(1) DEFAULT 'Y',
CONSTRAINT PK_COLOR PRIMARY KEY(COLOR_ID),
CONSTRAINT FK_COLOR_MODEL FOREIGN KEY (MODEL_ID) references ORDER_MANAGEMENT_MODEL (MODEL_ID)
);

CREATE TABLE ORDER_MANAGEMENT_DETAILS(
ORDER_ID int NOT NULL AUTO_INCREMENT,
SERIES_NAME varchar(225),
MODEL_NAME varchar(255),
ACCESSORY_NAME varchar(255),
PRICE decimal(10,2),
COLOR_NAME varchar(255),
CONSTRAINT PK_ORDER PRIMARY KEY(ORDER_ID)
);



CREATE TABLE ORDER_MANAGEMENT_USERS(
ID int NOT NULL AUTO_INCREMENT,
USER_NAME varchar(30),
USER_PASSWORD varchar(30),
IS_ADMIN varchar(1),
CONSTRAINT PK_ID PRIMARY KEY(ID)
);


CREATE TABLE ORDER_MANAGEMENT_ORDERDETAILS(
ORDER_ID int NOT NULL AUTO_INCREMENT,
SERIES_NAME varchar(225),
MODEL_NAME varchar(255),
PRICE decimal(10,2),
CONSTRAINT PK_ORDER PRIMARY KEY(ORDER_ID)
);


CREATE TABLE ORDER_MANAGEMENT_COLORDETAILS(
ID int NOT NULL AUTO_INCREMENT,
ACCESSORY_NAME varchar(255),
ORDER_ID int NOT NULL,
COLOR_NAME varchar(255),
CONSTRAINT PK_ID PRIMARY KEY(ID),
CONSTRAINT FK_ORDER_DETAILS FOREIGN KEY (ORDER_ID) references ORDER_MANAGEMENT_ORDERDETAILS (ORDER_ID)
);